/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5P1s8U1ouwj
 */
import React from 'react';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { Button } from './ui/button';

export function GenerationCard() {
  return (
    <div
      key="1"
      className="bg-[#1a1a1a] text-white p-4 rounded-lg max-w-md"
    >
      <h2 className="text-xl font-bold mb-4">Create a round thumbnail...</h2>
      <div className="flex items-center mb-4">
        <PencilIcon className="text-blue-500 mr-2" />
        <h3 className="text-lg font-semibold">Leonardo Diffusion XL</h3>
      </div>
      <div className="grid grid-cols-2 gap-4 mb-4">
        <div>
          <p className="text-sm font-medium text-gray-400">Input Resolution</p>
          <p className="text-sm">512 × 512px</p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Created</p>
          <p className="text-sm">06/01/24 at 12:48 PM</p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Pipeline</p>
          <div className="flex items-center">
            <CheckCircleIcon className="text-green-500 mr-1" />
            <p className="text-sm">Alchemy V2</p>
          </div>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Seed</p>
          <p className="text-sm">
            <Input
              className="bg-[#333333] border border-gray-400 text-white"
              defaultValue="624471552"
              type="number"
            />
          </p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Preset</p>
          <p className="text-sm">Dynamic</p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Prompt Magic</p>
          <p className="text-sm">-</p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">Init Strength</p>
          <p className="text-sm">No init image</p>
        </div>
        <div>
          <p className="text-sm font-medium text-gray-400">High Contrast</p>
          <p className="text-sm">-</p>
        </div>
      </div>
      <Textarea
        className="bg-[#333333] text-white mb-4"
        placeholder="ski slope in the alps. beautiful weather, bright sunshine, beautiful snow-covered slope, ski run between snow-covered spruce trees. blue, yellow, orange flags, happy people, big mountains in background"
        style={{
          color: 'white',
        }}
      />
      <Textarea
        className="bg-[#4d4d4d] text-gray-400 mb-4"
        placeholder="ski slope in the alps. beautiful weather, bright sunshine, beautiful snow-covered slope, ski run between snow-covered spruce trees. blue, yellow, orange flags, happy people, big mountains in background"
      />
      <Button className="bg-blue-500 hover:bg-blue-600 w-full py-3 rounded-md">
        Regenerate
      </Button>
    </div>
  );
}

function PencilIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  );
}

function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}
