/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/azbQ0q7MBtW
 */
import React from 'react';
import { CardTitle, CardHeader, CardContent, Card } from './ui/card';
import { VariantCard } from 'leonardo-ai-gallery';
import { GenerationCard } from './generation-card';

export function Generation(props) {
  return (
    <section className="dark w-full bg-gradient-to-r from-gray-900 to-blue-900 text-white py-12 px-8">
      <div className="mx-auto flex flex-row justify-start items-start gap-10">
        <div className="md:col-span-1 min-w-[400px]">
          <GenerationCard {...props} />
        </div>
        <div
          className="md:col-span-2 grid md:grid-cols-4 gap-4"
          style={{
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
          }}
        >
          <VariantCard />
          <VariantCard />
          <VariantCard />
          <VariantCard />
          <VariantCard />
          <VariantCard />
          <VariantCard />
        </div>
      </div>
    </section>
  );
}

function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  );
}
