import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4">
          <ul className="flex flex-row gap-6">
            <li style={{ marginRight: 6 }}>
              <Link href="/">Home</Link>
            </li>
            <li style={{ marginRight: 6 }}>
              <Link href="/model">Model</Link>
            </li>
            <li style={{ marginRight: 6 }}>
              <Link href="/components">Components</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
